name: ci

on:
  push:
    branches:
      - main

jobs:
  container:
    strategy:
      matrix:
        img: [load, result, vote, worker, worker-go]
        os: [linux]
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: |
            latest=true
          tags: |
            type=raw,value=latest
      -
        name: Build and push GHCR load
        id: docker_build_ghcr_load
        uses: docker/build-push-action@v3
        with:
          file: "./voting/${{ matrix.img }}/Dockerfile"
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          build-args:
            BUILDPLATFORM=${{ matrix.os }}/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
