name: deploy-result

on:
  push:
    branches:
    - $default-branch

jobs:
  result:
    runs-on: ubuntu-latest
    env:
      working-directory: ./voting/result
    steps:
      # env variable of repository, because repository must be lowercase
      - 
        name: lowercase repository
        run: |
          echo REPO=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Github Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
#      # currently disabled due to beta status
#      -
#        name: Login to Github Container Registry
#        uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push gitlab pkg
        id: docker_build_ghpkg
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.working-directory }}
          push: true
          tags: |
            docker.pkg.github.com/${{ env.REPO }}/result
#            ghcr.io/${{ env.REPO }}/result
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}:latest
  vote:
    runs-on: ubuntu-latest
    env:
      working-directory: ./voting/vote
    steps:
      # env variable of repository, because repository must be lowercase
      - 
        name: lowercase repository
        run: |
          echo REPO=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Github Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
#      # currently disabled due to beta status
#      -
#        name: Login to Github Container Registry
#        uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push gitlab pkg
        id: docker_build_ghpkg
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.working-directory }}
          push: true
          tags: |
            docker.pkg.github.com/${{ env.REPO }}/vote:latest
#            ghcr.io/${{ env.REPO }}/vote
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  worker:
    runs-on: ubuntu-latest
    env:
      working-directory: ./voting/worker
    steps:
      # env variable of repository, because repository must be lowercase
      - 
        name: lowercase repository
        run: |
          echo REPO=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Github Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
#      # currently disabled due to beta status
#      -
#        name: Login to Github Container Registry
#        uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push gitlab pkg
        id: docker_build_ghpkg
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.working-directory }}
          push: true
          tags: |
            docker.pkg.github.com/${{ env.REPO }}/worker:latest
#            ghcr.io/${{ env.REPO }}/worker
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  worker-go:
    runs-on: ubuntu-latest
    env:
      working-directory: ./voting/worker-go
    steps:
      # env variable of repository, because repository must be lowercase
      - 
        name: lowercase repository
        run: |
          echo REPO=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Github Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
#      # currently disabled due to beta status
#      -
#        name: Login to Github Container Registry
#        uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push gitlab pkg
        id: docker_build_ghpkg
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.working-directory }}
          push: true
          tags: |
            docker.pkg.github.com/${{ env.REPO }}/worker:latest
#            ghcr.io/${{ env.REPO }}/worker
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  load:
    runs-on: ubuntu-latest
    env:
      working-directory: ./voting/load
    steps:
      # env variable of repository, because repository must be lowercase
      - 
        name: lowercase repository
        run: |
          echo REPO=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Github Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
#      # currently disabled due to beta status
#      -
#        name: Login to Github Container Registry
#        uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push gitlab pkg
        id: docker_build_ghpkg
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.working-directory }}
          push: true
          tags: |
            docker.pkg.github.com/${{ env.REPO }}/worker:latest
#            ghcr.io/${{ env.REPO }}/worker
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
